name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Make build.sh Executable
        run: chmod +x build.sh

      - name: Install npm Dependencies
        run: npm install

      - name: Run Build Script
        run: ./build.sh