name: Build



on:
  push:
    branches:
      - main
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Make build.sh Executable
        run: chmod +x build.sh

      - name: Install npm Dependencies
        run: npm install

      - name: bundle.js hash before
        run: sha256sum lightweight_charts_/js/bundle.js

      - name: Run Build Script
        run: ./build.sh

      # - name: Update resources
      #   uses: test-room-7/action-update-file@v2.0.0
      #   with:
      #       file-path: | 
      #         lightweight_charts_/js/bundle.js
      #         lightweight_charts/js/bundle.js
      #         lightweight_charts/js/lightweight-charts.js
      #         lightweight_charts/js/styles.css
      #       commit-msg: Update resources
      #       github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: bundle.js hash after
        run: sha256sum lightweight_charts_/js/bundle.js

      - name: Commit and Push Changes
        run: |
          git --no-pager status
          git diff --name-only
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lightweight_charts_/js/bundle.js lightweight_charts/js/bundle.js lightweight_charts/js/lightweight-charts.js lightweight_charts/js/styles.css
          git commit -m "Update resources [skip ci]" || echo "No changes to commit"
          git push