name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Use the repo token for pushing changes

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Make build.sh Executable
        run: chmod +x build.sh

      - name: Install npm Dependencies
        run: npm install

      - name: Run Build Script
        run: ./build.sh

      - name: Update resources
        uses: test-room-7/action-update-file@v2.0.0
        with:
            file-path: lightweight_charts_/bundle.js
            file-path: lightweight_charts/js/bundle.js
            file-path: lightweight_charts/js/lightweight_charts.js
            file-path: lightweight_charts/js/style.css
            commit-msg: Update resources
            github-token: ${{ secrets.GITHUB_TOKEN }}
